on:
  push:
    branches:
      - main

jobs:
  call-sniff:
    uses: JoaoVgon/twilio-conversations-demo-react-workflows/.github/workflows/sniffer-reusable.yml
    with:
      thresholds.large-component: '-1'
      thresholds.too-many-props: '-1'
      thresholds.inheritance-instead-of-composition: '-1'
      thresholds.props-in-initial-state: '-1'
      thresholds.direct-dom-manipulation: '-1'
      thresholds.force-update: '-1'
      thresholds.jsx-outside-render-method: '-1'
      thresholds.uncontrolled-components: '-1'
      thresholds.large-file: '-1'
